### ISSUE TITLE
Dark Mode readability

### ISSUE THREAD

**Issue by ghost** [makerdao/governance-dashboard#5]
In Dark Mode, the "No active or pending off-chain polls at the moment" text is hard to read, screenshot below:

![image](https://user-images.githubusercontent.com/86251124/177360952-e6dbf869-7499-4dc6-80d6-e4af13aef2d1.png)

**Comment by ghost** [comment]
@hernandoagf

**Comment by hernandoagf** [comment]
Thank you, I'll push a quick update to fix this :)

**Comment by hernandoagf** [comment]
This is fixed on staging and will be live on the next production build https://staging.makerdao-governance-dashboard.com/
