### ISSUE TITLE
display un"official" slates

### ISSUE THREAD

**Issue by nmushegian** [makerdao/governance-dashboard#65]
Assuming "all slates" can be its own tab and lazy loaded, is there any technical reason we can't show them? (IE someone mentioned spam, but you can load N at a time, and have a "go to slate" by hash).

The point is people need to be able to find and vote on proposals using whichever interface the organization endorses as official/secure.

**Comment by levity** [comment]
There's no iterable data structure for slates in ds-chief, so we would have to get the list from [Etch](https://github.com/dapphub/ds-chief/blob/master/src/chief.sol#L38) event logs, either upon request or in a prefetch process that puts them into another database (e.g. Vulcanize).

**Comment by nmushegian** [comment]
replacing with https://github.com/makerdao/governance-dashboard/issues/67
